"""Resize form inputs

Revision ID: 8692ee5c1c4c
Revises: a576412bdb4e
Create Date: 2020-09-28 17:13:59.171985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8692ee5c1c4c'
down_revision = 'a576412bdb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
